# Generated by Django 3.2.5 on 2021-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210725_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='soc',
            field=models.FloatField(),
        ),
    ]
